config/routes.rb
Rails.application.routes.draw do
  resources :choices
  # Home Page Route
  root to: "welcome#index"

  # About Page Route
  get "/about", to: "welcome#about", as: "about"

  # User Routes
  resources :users
  get "/profile", to: "users#show", as: "profile"
  get "/survey", to: "users#new_survey", as: "new_survey"
  post "/survey", to: "users#create_survey", as: "create_survey"
  get "/survey/edit", to: "users#edit_survey", as: "edit_survey"
  patch "/survey", to: "users#update_survey", as: "update_survey"
  delete "/survey", to: "users#delete_survey", as: "delete_survey"
  get "/results", to: "users#results", as: "results"

  # Policy Routes
  resources :policies

  # Session Routes
  get "/sign_in", to: "sessions#new"
  post "/sessions", to: "sessions#create"
  delete "/sessions", to: "sessions#destroy", as: "logout"
  
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	has_many :choices
	
	# User validations
	validates_presence_of :first_name, :last_name, :location, :party, :email, :profile_pic, :password 
	validates :email, uniqueness: true
	validates :password, length: {minimum: 6}

	# Confirmation logic for user model
	def self.confirm(params)
		@user = User.find_by({email: params[:email]})
		@user.try(:authenticate, params[:password])
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # Sets up authorization
  before_action :logged_in?, only: [:show, :edit, :update, :destroy, :new_survey, :results]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
    @user = current_user
    @choices = @user.choices
    @policies = Policy.all
    
    # Call for Math to calculate compatibility with candidates
    if @choices.empty? == false
      @hillary_compatible = Policy.compatibility_check(@user)[0]
      @trump_compatible = Policy.compatibility_check(@user)[1]
      @hillary_counter = Policy.compatibility_check(@user)[2]
      @trump_counter = Policy.compatibility_check(@user)[3]
    end
  end  

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  def create
    @user = User.new(user_params)
    if @user.save
      login(@user) # <-- login the user
      redirect_to profile_path # <-- go to show
    else
      # Error handling
      temp = @user.errors.full_messages.join(", ")
      render :json => temp
    end
  end

  # PATCH/PUT /users/1
  def update
    @user = User.find(params[:id])
    @user.update_attributes(user_params)
    redirect_to profile_path
  end

  # DELETE /users/1
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

# Below are survey methods for the user
# Provides RESTful actions for user surveys
  
  # Main survey screen
  def new_survey
    @user = current_user
    @choices = @user.choices
    # Re-route user if survey has already been taken
    if @choices.empty? == false
      redirect_to results_path
    else 
      @policies = Policy.all
      render :new_survey
    end
  end

  # Save survey results to choices model
  # This is NOT DRY or scalable. Needs work. But works...
  def create_survey
    # Grab all answers
    answer1 = params[:policy_1]
    answer2 = params[:policy_2]
    answer3 = params[:policy_3]
    answer4 = params[:policy_4]
    answer5 = params[:policy_5]
    answer6 = params[:policy_6]
    answer7 = params[:policy_7]
    answer8 = params[:policy_8]
    answer9 = params[:policy_9]
    answer10 = params[:policy_10]
    answer11 = params[:policy_11]
    answer12 = params[:policy_12]
    
    # Create 12 choices in the DB
    choice1 = Choice.new()
      choice1.choice = answer1
      choice1.policy_id = 1
      choice1.user_id = current_user.id
    choice1.save

    choice2 = Choice.new()
      choice2.choice = answer2
      choice2.policy_id = 2
      choice2.user_id = current_user.id
    choice2.save

    choice3 = Choice.new()
      choice3.choice = answer3
      choice3.policy_id = 3
      choice3.user_id = current_user.id
    choice3.save

    choice4 = Choice.new()
      choice4.choice = answer4
      choice4.policy_id = 4
      choice4.user_id = current_user.id
    choice4.save
    
    choice5 = Choice.new()
      choice5.choice = answer5
      choice5.policy_id = 5
      choice5.user_id = current_user.id
    choice5.save
    
    choice6 = Choice.new()
      choice6.choice = answer6
      choice6.policy_id = 6
      choice6.user_id = current_user.id
    choice6.save

    choice7 = Choice.new()
      choice7.choice = answer7
      choice7.policy_id = 7
      choice7.user_id = current_user.id
    choice7.save

    choice8 = Choice.new()
      choice8.choice = answer8
      choice8.policy_id = 8
      choice8.user_id = current_user.id
    choice8.save

    choice9 = Choice.new()
      choice9.choice = answer9
      choice9.policy_id = 9
      choice9.user_id = current_user.id
    choice9.save

    choice10 = Choice.new()
      choice10.choice = answer10
      choice10.policy_id = 10
      choice10.user_id = current_user.id
    choice10.save

    choice11 = Choice.new()
      choice11.choice = answer11
      choice11.policy_id = 11
      choice11.user_id = current_user.id
    choice11.save

    choice12 = Choice.new()
      choice12.choice = answer12
      choice12.policy_id = 12
      choice12.user_id = current_user.id
    choice12.save

    redirect_to results_path
  end

  # Edit method for survey
  # Also not DRY - also needs work.
  def edit_survey
    @user = current_user
    @choices = @user.choices
    @policies = Policy.all
    render :edit_survey
  end

  # Save updates to DB
  def update_survey
    @user = current_user
    @choices = @user.choices

    answer1 = params[:policy_1]
    answer2 = params[:policy_2]
    answer3 = params[:policy_3]
    answer4 = params[:policy_4]
    answer5 = params[:policy_5]
    answer6 = params[:policy_6]
    answer7 = params[:policy_7]
    answer8 = params[:policy_8]
    answer9 = params[:policy_9]
    answer10 = params[:policy_10]
    answer11 = params[:policy_11]
    answer12 = params[:policy_12]

    @choices.find_by(policy_id: 1).update_attributes({choice: answer1})
    @choices.find_by(policy_id: 2).update_attributes({choice: answer2})
    @choices.find_by(policy_id: 3).update_attributes({choice: answer3})
    @choices.find_by(policy_id: 4).update_attributes({choice: answer4})
    @choices.find_by(policy_id: 5).update_attributes({choice: answer5})
    @choices.find_by(policy_id: 6).update_attributes({choice: answer6})    
    @choices.find_by(policy_id: 7).update_attributes({choice: answer7})
    @choices.find_by(policy_id: 8).update_attributes({choice: answer8})
    @choices.find_by(policy_id: 9).update_attributes({choice: answer9})
    @choices.find_by(policy_id: 10).update_attributes({choice: answer10})
    @choices.find_by(policy_id: 11).update_attributes({choice: answer11})
    @choices.find_by(policy_id: 12).update_attributes({choice: answer12})

    redirect_to results_path
  end

  # Delete a survey
  def delete_survey
    @user = current_user
    @choices = @user.choices
    
    @choices.each do |choice|
      choice.destroy
    end
    
    redirect_to user_path(@user)
  end

  # View survey results
  def results
    @policies = Policy.all
    @user = current_user
    @choices = @user.choices
    
    # Call for Math to calculate compatibility with candidates
    if @choices.empty? == false
      @hillary_compatible = Policy.compatibility_check(@user)[0]
      @trump_compatible = Policy.compatibility_check(@user)[1]
      @hillary_counter = Policy.compatibility_check(@user)[2]
      @trump_counter = Policy.compatibility_check(@user)[3]
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :location, :party, :email, :profile_pic, :password)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_custom_flash.html.erb
<div id='flash-notice'>
<%= flash[:error] %> 
</div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <div class="field">
    <%= f.text_field :first_name, placeholder: "First Name" %>
  </div>

  <div class="field">
    <%= f.text_field :last_name, placeholder: "Last Name" %>
  </div>

  <div class="field">
    <%= f.text_field :location, placeholder: "location" %>
  </div>

  <div class="field">
    <%= f.text_field :party, placeholder: "party" %>
  </div>

  <div class="field">
    <%= f.text_field :email, placeholder: "email" %>
  </div>

  <div class="field">
    <%= f.text_field :profile_pic, placeholder: "profile picture url" %>
  </div>

  <div class="field">
    <%= f.password_field :password, placeholder: "password" %>
  </div>

  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="modal-dialog">
    <!-- Modal content-->
    <div class="page-content">
       	<div class="container">
    	<br>
            <div class="col-md-6 offset-md-3 col-xs-10 offset-xs-1"> 
	            <div class="modal-body">
		            <div class="login-header text-center">
		               <h3 class="modal-title">Edit Profile</h3>
		           	</div>
	           		<div class="modal-box">
			            <%= form_for @user do |f| %>
			               <div class="form-group register_user_username">
			                 <label for="first_name">First Name:</label>
			                 <%= f.text_field :first_name, placeholder: "First Name", :class => 'form-control' %>
			               </div>
			               <div class="form-group register_user_username">
			                 <label for="last_name">Last Name:</label>
			                 <%= f.text_field :last_name, placeholder: "Last Name", :class => 'form-control' %>
			               </div>
			               <div class="form-group register_user_username">
			                 <label for="party">Political Party:</label>
			                 <%= f.text_field :party, placeholder: "Political Party", :class => 'form-control' %>
			               </div>
			               <div class="form-group register_user_username">
			                 <label for="location">Location:</label>
			                 <%= f.text_field :location, placeholder: "eg. Cincinnat, OH", :class => 'form-control' %>
			               </div>
			               <div class="form-group register_user_username">
			                 <label for="profile_pic">Profile Photo:</label>
			                 <%= f.text_field :profile_pic, placeholder: "Link to Profile Photo", :class => 'form-control' %>
			               </div>
			               <div class="form-group register_user_username">
			                 <label for="email">Email:</label>
			                 <%= f.text_field :email, placeholder: "Email", :class => 'form-control' %>
			               </div>
			               <div class="form-group register_user_username">
			                 <label for="password_digest">Password:</label>
			                 <%= f.password_field :password, placeholder: "Password", :class => 'form-control' %>
			               </div> 
			               <div class="form-group register_user-buttons">
			                <%= f.submit "Submit", :class => 'btn btn-default btn-login-submit' %>
			                <button type="button" class="btn btn-default btn-login-action" data-dismiss="modal" aria-hidden="true">Cancel</button>
		                	</div>
		             	<% end %>
	            	</div>
	        	</div>
        	</div>	
    	</div>
	</div>
</div>

app/views/users/edit_survey.html.erb
<div class="survey-background">
	<div class="container form-container">
		<div class="col-md-12">
			<div class="entire-form">
			<%= form_tag(update_survey_path, method: "patch") do |f| %>
				  	<% @policies.each do |policy| %>
						<div class="col-md-12 each-policy-div">
						  	<div class="col-md-12 name-and-description">
							    <h3 class="policy-name-survey"><%= policy.name %></h3>
							    <div class="col-md-3 offset-md-2 col-xs-6">
							    	<p class="policy-left-description"><%= policy.left %></p>
							    </div>
							    <div class="col-md-3">
							    </div>
							    <div class="col-md-3 offset-md-2 col-xs-6">
							    	<p class="policy-right-description"><%= policy.right %></p>
							    </div>
							</div>	
							<div class="input-group">
								<div class="col-md-12 survey-buttons">    	
								    <input class="left-survey-button" style="height:35px; width:35px;" name="policy_<%=policy.id%>" type="radio" value="Left" required>
								    <input class="middle-survey-button" style="height:35px; width:35px;" name="policy_<%=policy.id%>" type="radio" value="Middle" required> 
								    <input class="right-survey-button" style="height:35px; width:35px;" name="policy_<%=policy.id%>" type="radio" value="Right" required> 
								</div>
							</div>	
						</div>
				  	<% end %>
					<div>
						<input class="survey-submit" type="submit" value="Submit">
					</div>	
				<% end %>
			</div>
		</div>
	</div>
<div>

app/views/users/new_survey.html.erb
<div class="survey-background">
	<div class="container form-container">
		<div class="col-md-12">
			<div class="entire-form">
			<div class="survey-page-header col-md-12">
				<p>Where Do You Stand?</p>
			</div>
			<%= form_tag do |f| %>
				  <% @policies.each do |policy| %>
				  
				  <div class="col-md-12 each-policy-div">
				  	<div class="col-md-12 name-and-description">
					    <h3 class="policy-name-survey"><%= policy.name %></h3>
						    <div class="col-md-3 offset-md-2 col-xs-6">
						    	<p class="policy-left-description"><%= policy.left %></p>
						    </div>
						    <div class="col-md-3">
						    </div>
						    <div class="col-md-3 offset-md-2 col-xs-6">
						    	<p class="policy-right-description"><%= policy.right %></p>
						    </div>
					</div>	
					<div class="input-group">
						<div class="col-md-12 survey-buttons">    	
						    <input class="left-survey-button" style="height:35px; width:35px;" name="policy_<%=policy.id%>" type="radio" value="Left" required>
						    <input class="middle-survey-button" style="height:35px; width:35px;" name="policy_<%=policy.id%>" type="radio" value="Middle" required> 
						    <input class="right-survey-button" style="height:35px; width:35px;" name="policy_<%=policy.id%>" type="radio" value="Right" required> 
						</div>
					</div>	
				   </div> 
				  
				  <% end %>
				  <div>
				  	<input class="survey-submit" type="submit" value="Submit">
				  </div>	
				<% end %>
			</div>
		</div>
	</div>
<div>

app/views/users/results.html.erb
<div class="row results-page-header">
    <h1>How Do You Stack Up?</h1>
  <div class="dashboard col-md-8 offset-md-2 col-xs-10 offset-xs-1">
  	<div class="col-md-6 col-xs-12 dashboard-column-left">
      	<div class="results-img-candidate-left" style="background-image: url('/images/HillaryOverlay.png')">
        	<h2><%=@hillary_compatible%>%</h2>
      	</div>
      	<p class="dashboard-subhead-left">Hillary Clinton</p>
      	<p class="dashboard-subhead2-left">Policies Matched: <%=@hillary_counter%>/12</p>
  	</div>
	  	<div class="col-md-6 col-xs-12">
	      	<div class="results-img-candidate-right" style="background-image: url('/images/TrumpOverlay.png')">
	        	<h2><%=@trump_compatible%>%</h2>
	      	</div>
	      	<p class="dashboard-subhead-right">Donald Trump</p>
	      	<p class="dashboard-subhead2-right">Policies Matched: <%=@trump_counter%>/12</p>
	  	</div>
  </div>
</div>

<!-- Main Content -->
<section class="results-background">
	<div class="results-box col-md-10 offset-md-1 col-xs-10 offset-xs-1">
	  <!-- Hillary Section -->
	  <div class="col-md-4 results-column">
	    <!-- Candidate Details -->
	    <div class="col-md-12 results-column-head">
	      <div class="candidate-img" style="background-image: url('images/Hillary.jpg')"></div>
	      <p class="candidate-name">Hillary Clinton</p>
	      <p>Party: <span class="candidate-party-left">Democrat</span></p>
	    </div>
	    <!-- Candidate Policies -->
	    <% @policies.each do |policy| %>
	      <div class="col-md-12 candidate-policies-box">
	        <p class="policy-name"><%= policy.name %></p>
	        <div class="col-md-5 offset-md-1 policy-value-left">
	          <p><%= policy.left %></p>
	        </div>
	        <div class="col-md-5 policy-value-right">
	          <p><%= policy.right %></p>
	        </div>
	        <% if policy.hillary_choice == "Left" %>
	          <div class="col-md-10 offset-md-1 policy-slider">
	            <img class="policy-slider-img" src="images/left-slider.png">
	          </div>
	        <% elsif policy.hillary_choice == "Middle" %>  
	          <div class="col-md-10 offset-md-1 policy-slider">
	            <img class="policy-slider-img" src="images/middle-slider.png">
	          </div>
	        <% else %> 
	          <div class="col-md-10 offset-md-1 policy-slider">
	            <img class="policy-slider-img" src="images/right-slider.png">
	          </div>  
	        <% end %>  
	      </div>
	      <div class="col-md-12">
	        <hr>
	      </div>
	    <% end %>
    	<%= button_to 'View More Resources', "https://www.hillaryclinton.com/", method: :get, class: 'see-more-button btn btn-outline-danger', :id => 'cta-button' %>
	  </div>

	  <!-- User Section -->
	  <div class="col-md-4 col-xs-12 results-column-user">
	    <div class="col-md-12 results-column-head">
	      <div class="candidate-img-results-page" style="background-image: url('<%=@user.profile_pic%>')"></div>
	      <p class="candidate-name"><%=@user.first_name%> <%=@user.last_name%></p>
	      <p>Party: <%=@user.party%></p>
	    </div>
	    <!-- Candidate Policies -->
	    <% @policies.each do |policy| %>
	      <div class="col-md-12 candidate-policies-box">
	        <p class="policy-name"><%= policy.name %></p>
	        <div class="col-md-5 offset-md-1 col-xs-6 policy-value-left">
	          <p><%= policy.left %></p>
	        </div>
	        <div class="col-md-5 col-xs-6 policy-value-right">
	          <p><%= policy.right %></p>
	        </div>
	        <% if @user.choices.find{|c| c.policy.id == policy.id}["choice"] == "Left" %>
	          <div class="col-md-10 offset-md-1 policy-slider">
	            <img class="policy-slider-img" src="images/left-slider.png">
	          </div>
	        <% elsif @user.choices.find{|c| c.policy.id == policy.id}["choice"] == "Middle" %>  
	          <div class="col-md-10 offset-md-1 policy-slider">
	            <img class="policy-slider-img" src="images/middle-slider.png">
	          </div>
	        <% else %> 
	          <div class="col-md-10 offset-md-1 policy-slider">
	            <img class="policy-slider-img" src="images/right-slider.png">
	          </div>  
	        <% end %>   
	      </div>
	      <div class="col-md-12">
	        <hr>
	      </div>
	    <% end %>
	    <%= button_to 'Edit Results', edit_survey_path, method: :get, class: 'see-more-button btn btn-outline-secondary', :id => 'cta-button' %>
	  </div>

	  <!-- Trump Section -->
	  <div class="col-md-4 results-column-right">
	    <div class="col-md-12 results-column-head">
	      <div class="candidate-img" style="background-image: url('images/Trump.jpg')"></div>
	      <p class="candidate-name">Donald Trump</p>
	      <p>Party: <span class="candidate-party-right">Republican</span></p>
	    </div>
	    <!-- Candidate Policies -->
	    <% @policies.each do |policy| %>
	      <div class="col-md-12 candidate-policies-box">
	        <p class="policy-name"><%= policy.name %></p>
	        <div class="col-md-5 offset-md-1 policy-value-left">
	          <p><%= policy.left %></p>
	        </div>
	        <div class="col-md-5 policy-value-right">
	          <p><%= policy.right %></p>
	        </div>
	        <% if policy.trump_choice == "Left" %>
	          <div class="col-md-10 offset-md-1 policy-slider">
	            <img class="policy-slider-img" src="images/left-slider.png">
	          </div>
	        <% elsif policy.trump_choice == "Middle" %>  
	          <div class="col-md-10 offset-md-1 policy-slider">
	            <img class="policy-slider-img" src="images/middle-slider.png">
	          </div>
	        <% else %> 
	          <div class="col-md-10 offset-md-1 policy-slider">
	            <img class="policy-slider-img" src="images/right-slider.png">
	          </div>  
	        <% end %>   
	      </div>
	      <div class="col-md-12">
	        <hr>
	      </div>
	    <% end %>
  		<%= button_to 'View More Resources', "https://www.donaldjtrump.com/", method: :get, class: 'see-more-button btn btn-outline-danger', :id => 'cta-button' %>
	  </div>
	</div>
</section>

app/views/users/show.html.erb
<!-- Hero Content  -->
<section class="profile-hero">
  <div class="profile-hero-graphic" style="background-image: url('<%= @user.profile_pic %>')">
  </div>
</section>

<div class="profile-header">
  <div class="profile-edit-button-box">
    <%= button_to 'Edit', edit_user_path(@user), method: :get, class: 'btn btn-outline-secondary', :id => 'profile-edit-button' %>
  </div>
  <div class="profile-img" style="background-image: url('<%= @user.profile_pic %>')"></div>
      <div class="profile-name">
          <p><%= @user.first_name %> <%= @user.last_name %></p>
     </div>
     <div class="profile-party">
       <p>Party: <span class="profile-party-value"><%= @user.party %></span> </p>
     </div>
     <div class="profile-details">
       <p><%= @user.location %> &nbsp&nbsp|&nbsp&nbsp <%= @user.email %></p>
     </div>
</div>


<section class="profile-content">
  <% if @choices.empty? == false %>
    <div class="survey-edit-button-box">
      <%= link_to 'Edit', edit_survey_path, method: :get, :id => 'survey-edit-button' %> &nbsp|&nbsp
      <%= link_to 'Delete', delete_survey_path, method: :delete, :id => 'survey-edit-button' %>
    </div>
    <p>Your Compatability Results</p>
    <div class="view-results-mobile">
      <div class="result-button"><%= button_to 'View Details', results_path, method: :get, class: 'btn btn-outline-danger', :id => 'cta-button' %></div>
    </div>
    <div class="col-md-2 offset-md-3 candidate-percent-box">
      <div class="candidate-percent">
        <div class="profile-img-candidate" style="background-image: url('/images/HillaryOverlay.png')">
          <p><%=@hillary_compatible%>%</p>
        </div>
      </div>
    </div>
    <div class="col-md-2">
      <div class="candidate-percent">
        <div class="result-button"><%= button_to 'View Details', results_path, method: :get, class: 'btn btn-outline-danger', :id => 'cta-button' %></div>
      </div>
    </div>
    <div class="col-md-2">
      <div class="candidate-percent">
        <div class="profile-img-candidate" style="background-image: url('/images/TrumpOverlay.png')">
            <p><%=@trump_compatible%>%</p>
        </div>
      </div>
    </div>
  <% else %>
    <div class="take-survey-box">
      <p>Want to See How You Compare to the Candidates?</p>
      <%= button_to 'Take the Survey', new_survey_path, method: :get, class: 'btn btn-outline-danger', :id => 'cta-button' %>
    </div>
  <% end %>
</section>
 
 