config/routes.rb
Rails.application.routes.draw do
  resources :choices
  # Home Page Route
  root to: "welcome#index"

  # About Page Route
  get "/about", to: "welcome#about", as: "about"

  # User Routes
  resources :users
  get "/profile", to: "users#show", as: "profile"
  get "/survey", to: "users#new_survey", as: "new_survey"
  post "/survey", to: "users#create_survey", as: "create_survey"
  get "/survey/edit", to: "users#edit_survey", as: "edit_survey"
  patch "/survey", to: "users#update_survey", as: "update_survey"
  delete "/survey", to: "users#delete_survey", as: "delete_survey"
  get "/results", to: "users#results", as: "results"

  # Policy Routes
  resources :policies

  # Session Routes
  get "/sign_in", to: "sessions#new"
  post "/sessions", to: "sessions#create"
  delete "/sessions", to: "sessions#destroy", as: "logout"
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Politicator</title>
	<%= csrf_meta_tags %>
	<!-- Set Viewport -->
	<meta name="viewport" content="width=device-width, initial-scale=1"/>
	<!-- Bootstrap CSS CDN -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.3/css/bootstrap.min.css">
	<!-- Local Styles -->
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<!-- Local Scripts -->
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<header>
	<!-- Navigation Bar -->
	<nav class="navbar navbar-fixed-top">
		<!--Burger navbar -->
		<button type="button" class="navbar-toggler hidden-md-up" data-toggle="collapse" data-target="#exCollapsingNavbar" aria-controls="exCollapsingNavbar" aria-expanded="false" aria-label="Toggle navigation"></button>
		<a class="navbar-brand" href="/">Politicator</a>
		<div class="collapse navbar-toggleable-sm" id="exCollapsingNavbar">
			<ul class="nav navbar-nav pull-md-left">
				<li class="nav-item"><a href="/" role="button">Home</a></li>
				<li class="nav-item"><%= link_to 'About Us', about_path, method: :get %></li>
				<li class="nav-item"><a href="/policies" role="button">Candidates</a></li>
				<li class="nav-item"><%= link_to 'Go to Survey', new_survey_path, method: :get %></li>
			</ul>
			<ul class="nav navbar-nav pull-md-right">
				<% if current_user == nil %>
	                <li class="nav-item"><a href="#loginModal" role="button" data-toggle="modal">Login</a></li>
	                <li class="nav-item"><a href="#registerModal" role="button" data-toggle="modal">Sign Up!</a></li>
				<% else %>
					<li class="nav-item mobile-hidden"><img class="img-rounded" src='<%=current_user.profile_pic%>' id="nav-photo"></li>
					<li class="nav-item"><a href="/profile" ><%=current_user.first_name%></a></li>
					<li class="nav-item"><%= link_to 'Logout', logout_path, method: :delete %></li>
				<% end %>
			</ul>
		</div>
	</nav>

	<!-- Register Modal -->
	<div id="registerModal" tabindex="-1" class="modal fade" role="dialog" aria-labelledby="registerModalLabel" aria-hidden="true">
	   <div class="modal-dialog">
		    <!-- Modal content-->
		    <div class="modal-content">
		       <div class="container">
		           <div class="modal-header">
		               <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		            </div>
		            <div class="col-sm-6 offset-sm-3"> 
			            <div class="modal-body">
			            <div id="register_modal_error" class="alert alert-info hidden" role="alert"></div>
				            <div class="login-header">
				               <h3 class="modal-title">Register</h3>
				           	</div>
			           		<div class="modal-box">
					            <%= form_for User.new do |f| %>
					               <div class="form-group register_user_username">
					                 <label for="first_name">First Name:</label>
					                 <%= f.text_field :first_name, placeholder: "First Name", :class => 'form-control' %>
					               </div>
					               <div class="form-group register_user_username">
					                 <label for="last_name">Last Name:</label>
					                 <%= f.text_field :last_name, placeholder: "Last Name", :class => 'form-control' %>
					               </div>
					               <div class="form-group register_user_username">
					                 <label for="party">Political Party:</label>
					                 <%= f.text_field :party, placeholder: "Political Party", :class => 'form-control' %>
					               </div>
					               <div class="form-group register_user_username">
					                 <label for="location">Location:</label>
					                 <%= f.text_field :location, placeholder: "eg. Cincinnat, OH", :class => 'form-control' %>
					               </div>
					               <div class="form-group register_user_username">
					                 <label for="profile_pic">Profile Photo:</label>
					                 <%= f.text_field :profile_pic, placeholder: "Link to Profile Photo", :class => 'form-control' %>
					               </div>
					               <div class="form-group register_user_username">
					                 <label for="email">Email:</label>
					                 <%= f.text_field :email, placeholder: "Email", :class => 'form-control' %>
					               </div>
					               <div class="form-group register_user_username">
					                 <label for="password_digest">Password:</label>
					                 <%= f.password_field :password, placeholder: "Password", :class => 'form-control' %>
					               </div> 
					               <div class="form-group register_user-buttons">
					                <%= f.submit "Submit", :id => "register-submit", :class => 'btn btn-default btn-login-submit' %>
					                <button type="button" class="btn btn-default btn-login-action" data-dismiss="modal" aria-hidden="true">Cancel</button>
				                	</div>
				             	<% end %>
			            	</div>
			        	</div>
		        	</div>	
		    	</div>
			</div>
		</div>
	</div>	


	<!-- Login Modal -->
	<div id="loginModal" tabindex="-1" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	   <div class="modal-dialog">
	       <!-- Modal content-->
	       <div class="modal-content">
		       <div class="container">
		           <div class="modal-header">
		               <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		           </div>
		           <div class="col-sm-6 offset-sm-3"> 
			           <div class="modal-body">
				           <div class="login-header">
				           		<h3 class="modal-title">User login</h3>
				           </div>

				           <div class="modal-box">
				                <%= form_for User.new, url: "/sessions", method: "post" do |f| %>
				                <div class="form-group user_username">
				                 <label for="email">Email:</label>
				                 <%= f.text_field :email, :class => "form-control" %>
				                </div>
				                <div class="form-group user-password">
				                 <label for="password_digest">Password:</label>
				                 <%= f.password_field :password, :class => "form-control" %>
				                </div> 
				                <div class="form-group user-buttons">
				                <%= f.submit "Sign In", :class => "btn btn-default btn-login-submit" %>
				                <button type="button" class="btn btn-default btn-login-action" data-dismiss="modal" aria-hidden="true">Cancel</button>
				                </div>
				               <% end %>
				            </div>
			       		</div>
		   			</div>
				</div>
			</div>
		</div>
	</div>
</header>

<%= yield %>

<!-- Footer Section -->
<section class="footer">
	<p class="footer-headline col-md-6 offset-md-3">More Resources</p>
	<ul class="footer-link-list col-md-6 offset-md-3">
		<li class="candidate-links"><a style="color: white" href="/resources">Our Candidate Resources</a></li> &nbsp&nbsp / &nbsp&nbsp
		<li class="candidate-links"><a style="color: white" href="https://www.hillaryclinton.com/" target="_blank">Clinton's Site</a></li> &nbsp&nbsp / &nbsp&nbsp
		<li class="candidate-links"><a style="color: white" href="https://www.donaldjtrump.com/" target="_blank">Trump's Site</a></li> &nbsp&nbsp / &nbsp&nbsp
		<li class="candidate-links"><a style="color: white" href="http://2016election.procon.org/view.source-summary-chart.php">Candidates Compared</a></li>
	</ul>
</section>

<!-- Scripts -->
	<!-- jQuery CDN -->
	<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
	<!-- Bootstrap JS CDN--> 
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.3/js/bootstrap.min.js"></script>
	<!-- Tether JS CDN--> 
	<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js"></script>
</body>
</html>